/* Generated by AN DISI Unibo */ 
package it.unibo.virtualrobot;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Virtualrobot extends QActorMsgQueue{
	public MsgHandle_Virtualrobot(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
