/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.virtualrobot4;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Virtualrobot4 extends AbstractVirtualrobot4 { 
	public Virtualrobot4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
