/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.virtualrobot5;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Virtualrobot5 extends AbstractVirtualrobot5 { 
	public Virtualrobot5(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
