/* Generated by AN DISI Unibo */ 
package it.unibo.ledhuelamp;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractLedhuelamp extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractLedhuelamp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/ledhuelamp/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/ledhuelamp/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForBlink",waitForBlink);
	    	stateTab.put("handleLedHueLampCmd",handleLedHueLampCmd);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "ledhuelamp tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"Inizializzazione led hue lamp\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://localhost:1883");
	    	//switchTo waitForBlink
	        switchToPlanAsNextState(pr, myselfName, "ledhuelamp_"+myselfName, 
	              "waitForBlink",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForBlink = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForBlink",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForBlink";  
	    	//bbb
	     msgTransition( pr,myselfName,"ledhuelamp_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleLedHueLampCmd") }, 
	          new String[]{"true","E","ledHueLampCmd" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForBlink){  
	    	 println( getName() + " plan=waitForBlink WARNING:" + e_waitForBlink.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForBlink
	    
	    StateFun handleLedHueLampCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleLedHueLampCmd",-1);
	    	String myselfName = "handleLedHueLampCmd";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ledHueLampCmd(\"blink\")");
	    	if( currentEvent != null && currentEvent.getEventId().equals("ledHueLampCmd") && 
	    		pengine.unify(curT, Term.createTerm("ledHueLampCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg = "\"javaRun con blink led hue lamp...\"";
	    			/* Print */
	    			parg =  updateVars( Term.createTerm("ledHueLampCmd(X)"), 
	    			                    Term.createTerm("ledHueLampCmd(\"blink\")"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) println( parg );
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("ledHueLampCmd(\"off\")");
	    	if( currentEvent != null && currentEvent.getEventId().equals("ledHueLampCmd") && 
	    		pengine.unify(curT, Term.createTerm("ledHueLampCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg = "\"javaRun per led hue lamp off...\"";
	    			/* Print */
	    			parg =  updateVars( Term.createTerm("ledHueLampCmd(X)"), 
	    			                    Term.createTerm("ledHueLampCmd(\"off\")"), 
	    				    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) println( parg );
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"ledhuelamp_"+myselfName,false,true);
	    }catch(Exception e_handleLedHueLampCmd){  
	    	 println( getName() + " plan=handleLedHueLampCmd WARNING:" + e_handleLedHueLampCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleLedHueLampCmd
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
