/* Generated by AN DISI Unibo */ 
package it.unibo.realrobot4;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realrobot4 extends QActorMsgQueue{
	public MsgHandle_Realrobot4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
