/* Generated by AN DISI Unibo */ 
package it.unibo.ctxAnalysisModel;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxAnalysisModel  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxanalysismodel", "./srcMore/it/unibo/ctxAnalysisModel/reqanalysismodel.pl", 
		"./srcMore/it/unibo/ctxAnalysisModel/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
