/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.virtualrobot2;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Virtualrobot2 extends AbstractVirtualrobot2 { 
	public Virtualrobot2(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
