/* Generated by AN DISI Unibo */ 
package it.unibo.notifier;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractNotifier extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractNotifier(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/notifier/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/notifier/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForFirstRequest",waitForFirstRequest);
	    	stateTab.put("startPolling",startPolling);
	    	stateTab.put("handleRequestTimeAndTemperature",handleRequestTimeAndTemperature);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "notifier tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"[INFO] Notifier START\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://localhost:1883");
	    	//switchTo waitForFirstRequest
	        switchToPlanAsNextState(pr, myselfName, "notifier_"+myselfName, 
	              "waitForFirstRequest",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForFirstRequest = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForFirstRequest",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForFirstRequest";  
	    	//bbb
	     msgTransition( pr,myselfName,"notifier_"+myselfName,false,
	          new StateFun[]{stateTab.get("startPolling") }, 
	          new String[]{"true","E","requestNotifier" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForFirstRequest){  
	    	 println( getName() + " plan=waitForFirstRequest WARNING:" + e_waitForFirstRequest.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForFirstRequest
	    
	    StateFun startPolling = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_startPolling",0);
	     pr.incNumIter(); 	
	    	String myselfName = "startPolling";  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(6000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "startPolling";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "requestExternalProvider","requestExternalProvider", guardVars ).toString();
	    	emit( "requestExternalProvider", temporaryStr );
	    	//bbb
	     msgTransition( pr,myselfName,"notifier_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleRequestTimeAndTemperature") }, 
	          new String[]{"true","E","temperatureTimeProviderResponse" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_startPolling){  
	    	 println( getName() + " plan=startPolling WARNING:" + e_startPolling.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//startPolling
	    
	    StateFun handleRequestTimeAndTemperature = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleRequestTimeAndTemperature",-1);
	    	String myselfName = "handleRequestTimeAndTemperature";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("temperatureTimeProviderResponse(V,T)");
	    	if( currentEvent != null && currentEvent.getEventId().equals("temperatureTimeProviderResponse") && 
	    		pengine.unify(curT, Term.createTerm("temperatureTimeProviderResponse(V,T)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			String parg="temperatureTimeRequest(V,T)";
	    			/* RaiseEvent */
	    			parg = updateVars(Term.createTerm("temperatureTimeProviderResponse(V,T)"),  Term.createTerm("temperatureTimeProviderResponse(V,T)"), 
	    				    		  					Term.createTerm(currentEvent.getMsg()), parg);
	    			if( parg != null ) emit( "temperatureTimeRequest", parg );
	    	}
	    	//switchTo startPolling
	        switchToPlanAsNextState(pr, myselfName, "notifier_"+myselfName, 
	              "startPolling",false, false, null); 
	    }catch(Exception e_handleRequestTimeAndTemperature){  
	    	 println( getName() + " plan=handleRequestTimeAndTemperature WARNING:" + e_handleRequestTimeAndTemperature.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleRequestTimeAndTemperature
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
