/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.realrobot4;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Realrobot4 extends AbstractRealrobot4 { 
	public Realrobot4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
