/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.humanoperator5;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Humanoperator5 extends AbstractHumanoperator5 { 
	public Humanoperator5(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
