/* Generated by AN DISI Unibo */ 
package it.unibo.applicationlogictemp;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Applicationlogictemp extends QActorMsgQueue{
	public MsgHandle_Applicationlogictemp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
