/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.fixedobstaclemanager;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Fixedobstaclemanager extends AbstractFixedobstaclemanager { 
	public Fixedobstaclemanager(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
