/* Generated by AN DISI Unibo */ 
package it.unibo.applicationlogiccmd;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Applicationlogiccmd extends QActorMsgQueue{
	public MsgHandle_Applicationlogiccmd(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
