/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.iss2018support.rover;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.rover.AbstractRover;

public class Rover extends AbstractRover { 
	public Rover(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
