/* Generated by AN DISI Unibo */ 
package it.unibo.applicationlogictime;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Applicationlogictime extends QActorMsgQueue{
	public MsgHandle_Applicationlogictime(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
