/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.virtualrobot3;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Virtualrobot3 extends AbstractVirtualrobot3 { 
	public Virtualrobot3(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
