/* Generated by AN DISI Unibo */ 
package it.unibo.movecorelogic;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractMovecorelogic extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractMovecorelogic(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/movecorelogic/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/movecorelogic/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForStart",waitForStart);
	    	stateTab.put("forwardOn",forwardOn);
	    	stateTab.put("handleRealSonarEvent",handleRealSonarEvent);
	    	stateTab.put("handleRealSonarEventFix",handleRealSonarEventFix);
	    	stateTab.put("handleVirtualSonarEvent",handleVirtualSonarEvent);
	    	stateTab.put("sonar2Detected",sonar2Detected);
	    	stateTab.put("stopPlan",stopPlan);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "movecorelogic tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "directionUpToDown";
	    	addRule( temporaryStr );  
	    	temporaryStr = "FirstColumn";
	    	addRule( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"d\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"d\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "init";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "\"[INFO] Inizializzazione del core della logica di movimento\"";
	    	println( temporaryStr );  
	     connectToMqttServer("tcp://192.168.1.112:1883");
	    	//switchTo waitForStart
	        switchToPlanAsNextState(pr, myselfName, "movecorelogic_"+myselfName, 
	              "waitForStart",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForStart = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForStart",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForStart";  
	    	//bbb
	     msgTransition( pr,myselfName,"movecorelogic_"+myselfName,false,
	          new StateFun[]{stateTab.get("forwardOn") }, 
	          new String[]{"true","E","coreCmdStart" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForStart){  
	    	 println( getName() + " plan=waitForStart WARNING:" + e_waitForStart.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForStart
	    
	    StateFun forwardOn = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_forwardOn",0);
	     pr.incNumIter(); 	
	    	String myselfName = "forwardOn";  
	    	temporaryStr = "\"[INFO] Piano ForwardON ...\"";
	    	println( temporaryStr );  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "forwardOn";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//bbb
	     msgTransition( pr,myselfName,"movecorelogic_"+myselfName,false,
	          new StateFun[]{stateTab.get("stopPlan"), stateTab.get("sonar2Detected"), stateTab.get("handleVirtualSonarEvent"), stateTab.get("handleRealSonarEvent") }, 
	          new String[]{"true","E","coreCmdStop", "true","E","roomSonar2Event", "true","E","virtualRobotSonarEvent", "true","E","realRobotSonarEvent" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_forwardOn){  
	    	 println( getName() + " plan=forwardOn WARNING:" + e_forwardOn.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//forwardOn
	    
	    StateFun handleRealSonarEvent = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_handleRealSonarEvent",0);
	     pr.incNumIter(); 	
	    	String myselfName = "handleRealSonarEvent";  
	    	temporaryStr = "\"[INFO] Trovato un ostacolo dal sonar reale, valutazione se mobile ...\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"stop\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEvent";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//bbb
	     msgTransition( pr,myselfName,"movecorelogic_"+myselfName,false,
	          new StateFun[]{stateTab.get("stopPlan"), stateTab.get("handleRealSonarEventFix"), stateTab.get("handleVirtualSonarEvent"), stateTab.get("sonar2Detected") }, 
	          new String[]{"true","E","coreCmdStop", "true","E","realRobotSonarEvent", "true","E","virtualRobotSonarEvent", "true","E","roomSonar2Event" },
	          5000, "forwardOn" );//msgTransition
	    }catch(Exception e_handleRealSonarEvent){  
	    	 println( getName() + " plan=handleRealSonarEvent WARNING:" + e_handleRealSonarEvent.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleRealSonarEvent
	    
	    StateFun handleRealSonarEventFix = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_handleRealSonarEventFix",0);
	     pr.incNumIter(); 	
	    	String myselfName = "handleRealSonarEventFix";  
	    	temporaryStr = "\"[INFO] Trovato ancora l'ostacolo, suppongo sia fisso\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"stop\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(2000,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "\"[INFO] Sonar virtuale ha ostacolo fisso!\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"d\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"a\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"a\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"d\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleRealSonarEventFix";
	    	if( ! aar.getGoon() ) return ;
	    	//bbb
	     msgTransition( pr,myselfName,"movecorelogic_"+myselfName,false,
	          new StateFun[]{stateTab.get("stopPlan"), stateTab.get("handleRealSonarEvent") }, 
	          new String[]{"true","E","coreCmdStop", "true","E","realRobotSonarEvent" },
	          8000, "forwardOn" );//msgTransition
	    }catch(Exception e_handleRealSonarEventFix){  
	    	 println( getName() + " plan=handleRealSonarEventFix WARNING:" + e_handleRealSonarEventFix.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleRealSonarEventFix
	    
	    StateFun handleVirtualSonarEvent = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleVirtualSonarEvent",-1);
	    	String myselfName = "handleVirtualSonarEvent";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " not !?justTurnedUpBottom" )) != null )
	    	{
	    	{//actionseq
	    	temporaryStr = "\"[INFO] Sonar virtuale ha trovato muro!\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"d\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleVirtualSonarEvent";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(800,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleVirtualSonarEvent";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"d\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "handleVirtualSonarEvent";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "justTurnedUpBottom";
	    	addRule( temporaryStr );  
	    	temporaryStr = "justTurnedBottomUp";
	    	removeRule( temporaryStr );  
	    	temporaryStr = "directionDownToUp";
	    	removeRule( temporaryStr );  
	    	temporaryStr = "directionUpToDown";
	    	addRule( temporaryStr );  
	    	temporaryStr = "firstWait";
	    	removeRule( temporaryStr );  
	    	temporaryStr = "secondWait";
	    	removeRule( temporaryStr );  
	    	};//actionseq
	    	}
	    	//switchTo forwardOn
	        switchToPlanAsNextState(pr, myselfName, "movecorelogic_"+myselfName, 
	              "forwardOn",false, false, null); 
	    }catch(Exception e_handleVirtualSonarEvent){  
	    	 println( getName() + " plan=handleVirtualSonarEvent WARNING:" + e_handleVirtualSonarEvent.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleVirtualSonarEvent
	    
	    StateFun sonar2Detected = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("sonar2Detected",-1);
	    	String myselfName = "sonar2Detected";  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " not !?justTurnedBottomUp" )) != null )
	    	{
	    	{//actionseq
	    	temporaryStr = "\"[INFO] Sonar2 raggiunto, non finito, SI SVOLTA!\"";
	    	println( temporaryStr );  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"a\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "sonar2Detected";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"w\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(100,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "sonar2Detected";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"a\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "sonar2Detected";
	    	if( ! aar.getGoon() ) return ;
	    	temporaryStr = "justTurnedBottomUp";
	    	addRule( temporaryStr );  
	    	temporaryStr = "justTurnedUpBottom";
	    	removeRule( temporaryStr );  
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?FirstColumn" )) != null ){
	    	temporaryStr = "FirstColumn";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	removeRule( temporaryStr );  
	    	}
	    	temporaryStr = "directionUpToDown";
	    	removeRule( temporaryStr );  
	    	temporaryStr = "directionDownToUp";
	    	addRule( temporaryStr );  
	    	temporaryStr = "firstWait";
	    	removeRule( temporaryStr );  
	    	temporaryStr = "secondWait";
	    	removeRule( temporaryStr );  
	    	};//actionseq
	    	}
	    	//switchTo forwardOn
	        switchToPlanAsNextState(pr, myselfName, "movecorelogic_"+myselfName, 
	              "forwardOn",false, false, null); 
	    }catch(Exception e_sonar2Detected){  
	    	 println( getName() + " plan=sonar2Detected WARNING:" + e_sonar2Detected.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//sonar2Detected
	    
	    StateFun stopPlan = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("stopPlan",-1);
	    	String myselfName = "stopPlan";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "robotCmd(Y)","robotCmd(\"stop\")", guardVars ).toString();
	    	emit( "robotCmd", temporaryStr );
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine, "coreHasFinished","coreHasFinished", guardVars ).toString();
	    	emit( "coreHasFinished", temporaryStr );
	    	temporaryStr = "\"[INFO] Corelogic fermata\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"movecorelogic_"+myselfName,false,
	          new StateFun[]{}, 
	          new String[]{},
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_stopPlan){  
	    	 println( getName() + " plan=stopPlan WARNING:" + e_stopPlan.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//stopPlan
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
