/* Generated by AN DISI Unibo */ 
package it.unibo.realrobot5;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Realrobot5 extends QActorMsgQueue{
	public MsgHandle_Realrobot5(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
