/* Generated by AN DISI Unibo */ 
package it.unibo.humanoperator5;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Humanoperator5 extends QActorMsgQueue{
	public MsgHandle_Humanoperator5(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
