/* Generated by AN DISI Unibo */ 
package it.unibo.timemitter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Timemitter extends QActorMsgQueue{
	public MsgHandle_Timemitter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
