/* Generated by AN DISI Unibo */ 
package it.unibo.sonar2;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sonar2 extends QActorMsgQueue{
	public MsgHandle_Sonar2(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
