/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.humanoperator4;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Humanoperator4 extends AbstractHumanoperator4 { 
	public Humanoperator4(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
