/* Generated by AN DISI Unibo */ 
package it.unibo.temperatureemitter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Temperatureemitter extends QActorMsgQueue{
	public MsgHandle_Temperatureemitter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
