/* Generated by AN DISI Unibo */ 
package it.unibo.ledhuelamp;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledhuelamp extends QActorMsgQueue{
	public MsgHandle_Ledhuelamp(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
