/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.appl2;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Appl2 extends AbstractAppl2 { 
	public Appl2(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
