/* Generated by AN DISI Unibo */ 
package it.unibo.robotmind;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractRobotmind extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractRobotmind(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/robotmind/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/robotmind/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForCmd",waitForCmd);
	    	stateTab.put("userCmdHandler",userCmdHandler);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "robotmind tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"robotmind START\"";
	    	println( temporaryStr );  
	    	temporaryStr = "isRealRobot";
	    	addRule( temporaryStr );  
	    	//switchTo waitForCmd
	        switchToPlanAsNextState(pr, myselfName, "robotmind_"+myselfName, 
	              "waitForCmd",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitForCmd",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitForCmd";  
	    	temporaryStr = "\"Robot in attesa di comandi\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"robotmind_"+myselfName,false,
	          new StateFun[]{stateTab.get("userCmdHandler") }, 
	          new String[]{"true","E","userCmd" },
	          3600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForCmd){  
	    	 println( getName() + " plan=waitForCmd WARNING:" + e_waitForCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForCmd
	    
	    StateFun userCmdHandler = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("userCmdHandler",-1);
	    	String myselfName = "userCmdHandler";  
	    	temporaryStr = "\"Valutazione TEMPERATURA ed ORARIO\"";
	    	println( temporaryStr );  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("userCmd(\"START\")");
	    	if( currentEvent != null && currentEvent.getEventId().equals("userCmd") && 
	    		pengine.unify(curT, Term.createTerm("userCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			{//actionseq
	    			temporaryStr = "\"Robot attivita' avviata\"";
	    			println( temporaryStr );  
	    			if( (guardVars = QActorUtils.evalTheGuard(this, " !?isRealRobot" )) != null ){
	    			temporaryStr = QActorUtils.unifyMsgContent(pengine, "ledCmd(X)","ledCmd(\"blink\")", guardVars ).toString();
	    			emit( "ledCmd", temporaryStr );
	    			}
	    			else{ temporaryStr = QActorUtils.unifyMsgContent(pengine, "ledHueLampCmd(X)","ledHueLampCmd(\"blink\")", guardVars ).toString();
	    			emit( "ledHueLampCmd", temporaryStr );
	    			}//delay  ( no more reactive within a plan)
	    			aar = delayReactive(5000,"" , "");
	    			if( aar.getInterrupted() ) curPlanInExec   = "userCmdHandler";
	    			if( ! aar.getGoon() ) return ;
	    			temporaryStr = "\"Trovato ostacolo fisso, cerco di evitarlo\"";
	    			println( temporaryStr );  
	    			temporaryStr = "\"Aggiungo l'ostacolo fisso alla posizione x in mappa\"";
	    			println( temporaryStr );  
	    			//delay  ( no more reactive within a plan)
	    			aar = delayReactive(5000,"" , "");
	    			if( aar.getInterrupted() ) curPlanInExec   = "userCmdHandler";
	    			if( ! aar.getGoon() ) return ;
	    			temporaryStr = "\"Trovato ostacolo mobile, cerco di evitarlo\"";
	    			println( temporaryStr );  
	    			//delay  ( no more reactive within a plan)
	    			aar = delayReactive(5000,"" , "");
	    			if( aar.getInterrupted() ) curPlanInExec   = "userCmdHandler";
	    			if( ! aar.getGoon() ) return ;
	    			temporaryStr = "\"Trovato ostacolo inevitabile, mi arresto\"";
	    			println( temporaryStr );  
	    			};//actionseq
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("userCmd(\"STOP\")");
	    	if( currentEvent != null && currentEvent.getEventId().equals("userCmd") && 
	    		pengine.unify(curT, Term.createTerm("userCmd(X)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			{//actionseq
	    			temporaryStr = "\"Robot attivita' arrestata\"";
	    			println( temporaryStr );  
	    			if( (guardVars = QActorUtils.evalTheGuard(this, " !?isRealRobot" )) != null ){
	    			temporaryStr = QActorUtils.unifyMsgContent(pengine, "ledCmd(X)","ledCmd(\"off\")", guardVars ).toString();
	    			emit( "ledCmd", temporaryStr );
	    			}
	    			else{ temporaryStr = QActorUtils.unifyMsgContent(pengine, "ledHueLampCmd(X)","ledHueLampCmd(\"off\")", guardVars ).toString();
	    			emit( "ledHueLampCmd", temporaryStr );
	    			}};//actionseq
	    	}
	    	//switchTo waitForCmd
	        switchToPlanAsNextState(pr, myselfName, "robotmind_"+myselfName, 
	              "waitForCmd",false, false, null); 
	    }catch(Exception e_userCmdHandler){  
	    	 println( getName() + " plan=userCmdHandler WARNING:" + e_userCmdHandler.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//userCmdHandler
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
