/* Generated by AN DISI Unibo */ 
package it.unibo.robotmind;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Robotmind extends QActorMsgQueue{
	public MsgHandle_Robotmind(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
