/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.humanoperator3;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Humanoperator3 extends AbstractHumanoperator3 { 
	public Humanoperator3(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
